name: vapeteka

publish_to: 'none'

version: 1.3.1+9

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.3
  get: ^4.3.8
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^1.0.3
  google_fonts: ^2.1.0
  mask_text_input_formatter: ^2.0.0
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.9
  firebase_core: ^1.10.2
  firebase_messaging: ^11.2.0
  flutter_local_notifications: ^9.1.4
  barcode_widget: ^2.0.1
  easy_localization: ^3.0.0
  provider: ^6.0.2
  double_back_to_close_app: ^2.0.1
  argon_buttons_flutter: ^1.1.0
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  fonts:
#    - family: Raleway
#      fonts:
#        - asset: fonts/Raleway-Regular.ttf
#        - asset: fonts/Raleway-Italic.ttf
#          style: italic
    - family: BlissPro
      fonts:
        - asset: fonts/BlissPro-Regular.otf
        - asset: fonts/BlissPro-Medium.otf
        - asset: fonts/BlissPro-Light.otf
        - asset: fonts/BlissPro-Heavy.otf
        - asset: fonts/BlissPro-Bold.otf
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/svg_icons/
